### ISSUE TITLE
Logic behind image start address

### ISSUE THREAD

**Issue by Igor-Misic** [ams-OSRAM-Group/tmf8820_21_28_driver_arduino#2]
This address `const unsigned long tmf8828_image_start       = 0x00200000;` here: [link](https://github.com/ams-OSRAM-Group/tmf8820_21_28_driver_arduino/blob/main/tmf8828_a/tmf8828_image.c#L613) 
that is eventually passed to function:
`static int8_t tmf8828BootloaderSetRamAddr ( tmf8828Driver * driver, uint16_t addr )`  here: [link](https://github.com/ams-OSRAM-Group/tmf8820_21_28_driver_arduino/blob/main/tmf8828_a/tmf8828.c#L588)

will be casted from original address  **0x00200000** to **0x0000**. 

 I am interested in the logic behind this code. Am I missing something here?

**Comment by MondayOnGitHub** [comment]
The function instructs the bootloader to select the RAM address range as destination. This defines the upper 16-bit of the address for this device. Only the offset (lower 16 address-bits) into the RAM range needs to be specified.

**Comment by Igor-Misic** [comment]
Thanks for the answer!
