### ISSUE TITLE
Setting the device to short range, high accuracy mode

### ISSUE THREAD

**Issue by AaronYoung5** [ams-OSRAM-Group/tmf8820_21_28_driver_arduino#3]
Hi! I would like to add the ability to set the active range register to the driver so I can enable short range, high accuracy mode. As a test, I'm currently just setting the register in the following way in the `tmf8828ConfigInternal` function. I can readout the raw histograms in both cases (w/ and w/o this code), but they both appear to be identical (i.e. long range mode).

```c
...
dataBuffer[0] = 110;
i2cTxReg(driver, driver->i2cSlaveAddress, 0x19, 110, dataBuffer);
stat = tmf8828WriteConfigPage(
    driver); // as a last step write the config page back
...
```

I'm using the latest code and I have a TMF8828. I have a retroreflective object about a 0.5 meters in front of the sensor and so I would expect a large spike in the histogram near bin 64 in short range mode, is that correct thinking?

Any insights would be much appreciated! I am reading out the register fine and I can see the default is 111. 

Thanks!!

**Comment by ptr814** [comment]
Hi AaronYoung5,
thank you for using our devices!
I think you have found an error in our datasheet, which we will correct - register 0x19 can only be used to read out the active range; the correct sequence to switch into short range high accuracy mode is correctly described in our [TMF8820/8821 Host Driver Communication](https://look.ams-osram.com/m/5bfe4f6d8a09e607/original/TMF882X-Host-Driver-Communication-AN001015.pdf) guide section 4.2.3:

![image](https://github.com/user-attachments/assets/bfa171d2-73d9-4f13-80e5-9bfefbb35c98)

Please also note that the i2cTxReg uses the number of bytes transferred as 4th parameter - https://github.com/ams-OSRAM/tmf8820_21_28_driver_arduino/blob/main/tmf8828_three/tmf8828_shim.h#L208C16-L208C56

I hope this clarifies the issue.

Thank you
Regards Peter

**Comment by AaronYoung5** [comment]
Hi Peter,

Thanks for the help! Worked great!

Aaron
